# Generated by Django 4.1.1 on 2022-09-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Combatant1',
            new_name='Combatant',
        ),
    ]
