# Generated by Django 4.1.1 on 2022-09-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0002_rename_combatant1_combatant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Combatant',
            new_name='Matches',
        ),
    ]
