# Generated by Django 4.1.1 on 2022-09-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0003_rename_combatant_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='combat',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='durability',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='name',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='power',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='strength',
        ),
        migrations.AddField(
            model_name='matches',
            name='durabilityP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='durabilityP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='imageP1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='matches',
            name='imageP2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='matches',
            name='intelligenceP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='intelligenceP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='nameP1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='matches',
            name='nameP2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='matches',
            name='powerP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='powerP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='realNameP1',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='matches',
            name='realNameP2',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='matches',
            name='speciesP1',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='matches',
            name='speciesP2',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='matches',
            name='speedP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='speedP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='strengthP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='strengthP2',
            field=models.IntegerField(default=0),
        ),
    ]
