# Generated by Django 4.1.1 on 2022-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0004_remove_matches_combat_remove_matches_durability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='durabilityP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='durabilityP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='intelligenceP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='intelligenceP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='powerP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='powerP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='speedP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='speedP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='strengthP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='strengthP2',
            field=models.IntegerField(default=0),
        ),
    ]
