# Generated by Django 4.1.1 on 2022-09-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0004_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='nameOfStage',
            field=models.CharField(default='0000000', max_length=32),
        ),
    ]
