# Generated by Django 4.1.1 on 2022-09-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0005_alter_matches_durabilityp1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='stageImg',
            field=models.TextField(default=''),
        ),
    ]
