# Generated by Django 4.1.1 on 2022-09-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0006_matches_stageimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='stageImg',
        ),
    ]
