# Generated by Django 4.1.1 on 2022-09-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0007_remove_matches_stageimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='matchName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
