# Generated by Django 4.1.1 on 2022-09-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0005_stage_nameofstage'),
        ('combat_ready_api', '0008_matches_matchname'),
    ]

    operations = [
    ]
