# Generated by Django 4.1.1 on 2022-09-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_ready_api', '0010_alter_stage_nameofstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='nameOfStage',
            field=models.CharField(default='0000000', max_length=500),
        ),
    ]
